In [87]:
import numpy as np 
import pandas as pd 

df=pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0     125.0   212    0      NaN    168.0      0      1.0   
1      53    1   0     140.0   203    1      0.0    155.0      1      3.1   
2      70    1   0     145.0   174    0      1.0    125.0      1      2.6   
3      61    1   0     148.0   203    0      1.0      NaN      0      0.0   
4      62    0   0     138.0   294    1      1.0    106.0      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1     140.0   221    0      1.0    164.0      1      0.0   
1021   60    1   0     125.0   258    0      0.0    141.0      1      2.8   
1022   47    1   0     110.0   275    0      0.0    118.0      1      1.0   
1023   50    0   0     110.0   254    0      0.0    159.0      0      0.0   
1024   54    1   0     120.0   188    0      1.0    113.0      0      1.4   

      slope   ca  thal  target  
0         2  2.0   3.0       0  
1         0  0.0   3.0       0  
2         0  0.0   3.0       0  
3         2  1.0   3.0       0  
4         1  3.0   2.0       0  
...     ...  ...   ...     ...  
1020      2  0.0   2.0       1  
1021      1  1.0   3.0       0  
1022      1  1.0   2.0       0  
1023      2  0.0   2.0       1  
1024      1  1.0   3.0       0  

[1025 rows x 14 columns]

In [88]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0     125.0   212    0      NaN    168.0      0      1.0      2   
1   53    1   0     140.0   203    1      0.0    155.0      1      3.1      0   
2   70    1   0     145.0   174    0      1.0    125.0      1      2.6      0   
3   61    1   0     148.0   203    0      1.0      NaN      0      0.0      2   
4   62    0   0     138.0   294    1      1.0    106.0      0      1.9      1   

    ca  thal  target  
0  2.0   3.0       0  
1  0.0   3.0       0  
2  0.0   3.0       0  
3  1.0   3.0       0  
4  3.0   2.0       0

In [89]:
df.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1     140.0   221    0      1.0    164.0      1      0.0   
1021   60    1   0     125.0   258    0      0.0    141.0      1      2.8   
1022   47    1   0     110.0   275    0      0.0    118.0      1      1.0   
1023   50    0   0     110.0   254    0      0.0    159.0      0      0.0   
1024   54    1   0     120.0   188    0      1.0    113.0      0      1.4   

      slope   ca  thal  target  
1020      2  0.0   2.0       1  
1021      1  1.0   3.0       0  
1022      1  1.0   2.0       0  
1023      2  0.0   2.0       1  
1024      1  1.0   3.0       0

In [90]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [91]:
df.shape

(1025, 14)

In [92]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps    float64
chol          int64
fbs           int64
restecg     float64
thalach     float64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal        float64
target        int64
dtype: object

In [93]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     1
thalach     1
exang       0
oldpeak     0
slope       0
ca          2
thal        1
target      0
dtype: int64

In [94]:
df['trestbps'].unique()

array([125., 140., 145., 148., 138., 100., 114., 160., 120., 122., 112.,
       132., 118., 128.,  nan, 124., 106., 104., 135., 130., 136., 180.,
       129., 150., 178., 146., 117., 152., 154., 170., 134., 174., 144.,
       108., 123., 110., 142., 126., 192., 115.,  94., 200., 165., 102.,
       105., 155., 172., 164., 156., 101.])

In [95]:
df['restecg'].unique()

array([nan,  0.,  1.,  2.])

In [96]:
df['thalach'].unique()

array([168., 155., 125.,  nan, 106., 122., 140., 145., 144., 116., 136.,
       192., 156., 142., 109., 162., 165., 148., 172., 173., 146., 179.,
       152., 117., 115., 112., 163., 147., 182., 105., 150., 151., 169.,
       166., 178., 132., 160., 123., 139., 111., 180., 164., 202., 157.,
       159., 170., 138., 175., 158., 126., 143., 141., 167.,  95., 190.,
       118., 103., 181., 108., 177., 134., 120., 171., 149., 154., 153.,
        88., 174., 114., 195., 133.,  96., 124., 131., 185., 194., 128.,
       127., 186., 184., 188., 130.,  71., 161., 137.,  99., 121., 187.,
        97.,  90., 129., 113.])

In [97]:
df['ca'].unique()

array([ 2.,  0.,  1.,  3., nan,  4.])

In [98]:
df['thal'].unique()

array([ 3.,  2.,  1.,  0., nan])

In [99]:
df['trestbps']=df['trestbps'].fillna(df['trestbps'].mean())
df['restecg']=df['restecg'].fillna(df['restecg'].mode()[0])
df['thalach']=df['thalach'].fillna(df['thalach'].mean())
df['ca']=df['ca'].fillna(df['ca'].mode()[0])
df['thal']=df['thal'].fillna(df['thal'].mode()[0])

In [100]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [101]:
x=df.iloc[:,:-1].values
x

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [102]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [103]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[59.,  1.,  1., ...,  2.,  0.,  2.],
       [58.,  1.,  0., ...,  1.,  3.,  3.],
       [44.,  0.,  2., ...,  1.,  1.,  2.],
       ...,
       [51.,  1.,  0., ...,  2.,  0.,  3.],
       [43.,  1.,  0., ...,  2.,  0.,  3.],
       [52.,  1.,  0., ...,  2.,  1.,  2.]])

In [104]:
x_test

array([[62.,  0.,  0., ...,  2.,  0.,  2.],
       [53.,  0.,  2., ...,  2.,  0.,  0.],
       [55.,  1.,  0., ...,  1.,  1.,  3.],
       ...,
       [70.,  1.,  2., ...,  1.,  1.,  3.],
       [67.,  1.,  0., ...,  1.,  2.,  2.],
       [64.,  1.,  2., ...,  2.,  0.,  2.]])

In [105]:
y_train

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,

In [106]:
y_test

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,

In [107]:
from sklearn.preprocessing import StandardScaler

scalar=StandardScaler()
scalar.fit(x_train)

x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)

In [108]:
x_train

array([[ 0.51227152,  0.64358464,  0.02931827, ...,  0.97708096,
        -0.72641166, -0.53812812],
       [ 0.40223597,  0.64358464, -0.92619093, ..., -0.65214474,
         2.11969304,  1.10373511],
       [-1.1382618 , -1.55379719,  0.98482748, ..., -0.65214474,
         0.22228991, -0.53812812],
       ...,
       [-0.36801292,  0.64358464, -0.92619093, ...,  0.97708096,
        -0.72641166,  1.10373511],
       [-1.24829735,  0.64358464, -0.92619093, ...,  0.97708096,
        -0.72641166,  1.10373511],
       [-0.25797736,  0.64358464, -0.92619093, ...,  0.97708096,
         0.22228991, -0.53812812]])

In [109]:
x_test

array([[ 0.84237819, -1.55379719, -0.92619093, ...,  0.97708096,
        -0.72641166, -0.53812812],
       [-0.14794181, -1.55379719,  0.98482748, ...,  0.97708096,
        -0.72641166, -3.82185458],
       [ 0.0721293 ,  0.64358464, -0.92619093, ..., -0.65214474,
         0.22228991,  1.10373511],
       ...,
       [ 1.72266262,  0.64358464,  0.98482748, ..., -0.65214474,
         0.22228991,  1.10373511],
       [ 1.39255596,  0.64358464, -0.92619093, ..., -0.65214474,
         1.17099147, -0.53812812],
       [ 1.0624493 ,  0.64358464,  0.98482748, ...,  0.97708096,
        -0.72641166, -0.53812812]])

In [110]:
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)

y_pred=knn.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,

In [111]:
print(knn.predict(scalar.transform([[66,1,1,138,252,1,0,155,1,2.2,2,1,2]])))

[0]


In [112]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)
cm

array([[127,  32],
       [ 17, 132]], dtype=int64)

In [113]:
from sklearn.metrics import accuracy_score

score=accuracy_score(y_test,y_pred)
score

0.8409090909090909

In [114]:
#Hyper parameter Tuning
from sklearn.model_selection import GridSearchCV

In [115]:
model1=KNeighborsClassifier()

In [116]:
param={'n_neighbors':[3,5,7,9],'weights':['uniform','distance']}
clf = GridSearchCV(model1,param,cv=10,scoring='accuracy')
#cv = cross validation

clf.fit(x_train,y_train) #k=3,w=uni, k=5,w=uni...

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [117]:
print(clf.best_params_)

{'n_neighbors': 9, 'weights': 'distance'}


In [118]:
model2=KNeighborsClassifier(n_neighbors=9,weights='distance')
model2.fit(x_train,y_train)
y_pred2=model2.predict(x_test)
y_pred2

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,

In [119]:
sc2=accuracy_score(y_test,y_pred2)
sc2

1.0